### PR TITLE
Adding autocomplete for interactive mode

### PR DESCRIPTION
**Pull request by Code-Hex**
# What I did?
I have created complementary functionality in interactive mode #38 
But I have something to do.

- [x] Create test for autocomplete.go
- [x] Simplifying autocomplete.go
- [x] In order not to end with `log.Fatal` etc, Allow all errors of runtime to be received from `runtime.Run`

I think @cloudson perform the last task earlier than me.

### CODE REVIEW

**Comment by cloudson** [comment]
Hey @Code-Hex , about the task 
> In order not to end with log.Fatal etc, Allow all errors of runtime to be received from runtime.Run

I fix the problem [here](In order not to end with log.Fatal etc, Allow all errors of runtime to be received from runtime.Run). The unit tests have passed but as this work is about the runtime package, I would like to you and @luizperes help me to test it manually. 
Basically, each (syntax, semantical and of runtime) error should not break the program on interactive mode.

**Comment by luizperes** [comment]
Hi @Code-Hex and @cloudson ! Gotcha! I will try to do my best on it!

**Comment by Code-Hex** [comment]
@cloudson Nice!!  Thanks for the quick work.
I will tell you when these are completed.

**Comment by Code-Hex** [comment]
@cloudson @luizperes my tasks complete.
I've added a comment @cloudson 's [task](https://github.com/cloudson/gitql/commit/e189609215dd61605d2cb4a0d9cd53a3e735488a).
Thank you.

**Comment by cloudson** [comment]
Thank you again @Code-Hex . You deserve a beer or tea.

**Pull request merged**
