### PR TITLE
Add 'like' functionality in where clause

### PR DESCRIPTION
**Pull request by jsixface**
Fixes may be first part of #59 
```
gitql 'select message, author from commits where message like "%author%"'
+--------------------------------+----------+
|            message             |  author  |
+--------------------------------+----------+
| support for full_message,      | cloudson |
| message, author, committer     |          |
+--------------------------------+----------+
```

### CODE REVIEW

**Comment by luizperes** [comment]
Hey @jsixface, I will check this one later as it has some file conflicts, ok?

**Comment by jsixface** [comment]
@luizperes The conflicts are due to the previous pull requests. 
The changes on that pull request and this one overlap. I'll fix them

**Comment by luizperes** [comment]
Thank you @jsixface, sorry, I haven't had the time to check your PR. Will try to do it over the weekend! :)

**Comment by jsixface** [comment]
@luizperes Sure. No hurry.

**Comment by luizperes** [comment]
Hi @cloudson, what do you think about that? :)

**Comment by cloudson** [comment]
It looks good for me, but I'm not sure about run like statement using escaped %. 
Anyway, I'm going to test it manually. 

Thanks @jsixface

**Comment by luizperes** [comment]
Sounds good @cloudson, please update us back :) thanks!

**Comment by cloudson** [comment]
Here I am. The Code is good for me @jsixface . 
Sorry for the delay to check it. 
I've tried to create a test with the literal % char and its failed but we can in another PR work on it.

**Pull request merged**
