### PR TITLE
Bugfix - order by asc/desc

### PR DESCRIPTION
**Pull request by jsixface**
Fixing the issue with the order by #50

### CODE REVIEW

**Comment by jsixface** [comment]
Hi @luizperes, I've added the test case for verifying the sorting

**Comment by luizperes** [comment]
Hi @jsixface, I will check it thoroughly and will update you back, thanks!

**Comment by luizperes** [comment]
Hi @jsixface, last time I checked I did not realize that your method `fieldContains` was inside the `commits.go` file. Please check my review regarding that. Other than that, LGTM! I am just waiting for this last modification and will merge it :)

**Comment by jsixface** [comment]
I'm sorry, do you mean test cases needed for `fieldContaines` method ?

**Comment by luizperes** [comment]
@jsixface No, I don't think that we will need test for the `fieldContains` method.
I mean that this method should not stay inside the `commits.go` file, as it is not really related to commits. The `fieldContains` method is a more like a helper method, and that is why I said to move it to a new file under `utilities/utilities.go` (which does not exist right now).
The structure of `gitql` would be:

- gitql
  - lexical
    - lexical.go
    - ... other files
  - parser
    - ... files related to parser
  - runtime
    - ... files related to runtime
  - semantical
    - ... files related to semantical step
  - utilities
    - utilities.go _// the method `fieldContains` would be inside this file_
  - Makefile
  - .gitignore
  - ... other files inside the root folder

**Comment by luizperes** [comment]
If you need more explanation, please do not hesitate do ask me :)

**Comment by jsixface** [comment]
This makes sense, I'll make this change. 
The only review I see is regarding the test cases. Never saw any regarding moving the `fieldContains` method.

**Comment by luizperes** [comment]
Hi @jsixface, just checking, any progress on that last change? :D Sorry for late reply

**Comment by luizperes** [comment]
Perfect! Thanks for making the tests as well!

**Pull request merged**
