### PR TITLE
Add not equals validation

### LINKED ISSUE #58: field not equal string
How to select first committer that is not me?

I've try this:

```sql
select committer from commits where committer <> 'Jakub Jankiewicz' order by date desc limit 1'
```

but got error:
```
Expected T_LITERAL and found T_GREATER
```

and this:

```sql
select committer from commits where committer != 'Jakub Jankiewicz' order by date desc limit 1
```

return:
```
+------------------+
|    committer     |
+------------------+
| Jakub Jankiewicz |
+------------------+
```

### PR DESCRIPTION
**Pull request by jsixface**
Add Not equals validation to the where clause.

```
gitql "select committer from commits where committer != 'Arumugam J' order by date desc limit 1"
+-----------+
| committer |
+-----------+
| GitHub    |
+-----------+
```
It was originally not validating the where clause if it has a `!=` sign. Fixes #58

### CODE REVIEW

**Comment by luizperes** [comment]
Hi @jsixface, is there any problem with the operator `<>` ? I am asking that because this is the actual `lexeme` for __not equals__ in SQL, right? Thanks! :)

**Comment by jsixface** [comment]
In my SQL experience, I've never used `<>` for not equal to. Is that the proper usage?

**Comment by luizperes** [comment]
what do you think of supporting both? (as per https://stackoverflow.com/questions/723195/should-i-use-or-for-not-equal-in-t-sql)

**Comment by jsixface** [comment]
yeah. I'll add support for `<>` as well.

**Comment by jsixface** [comment]
@luizperes Added the operator `<>` for not equal to.

**Comment by luizperes** [comment]
Sounds good @jsixface! Thanks for your contributions and sorry for the delay in reviewing it. :)

**Pull request merged**
